# Generated by Django 3.0.6 on 2020-05-25 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_image_picha_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
    ]
